version:               2
jobs:
  build:
    machine:           true
    working_directory: ~/ftgo-monolith
    steps:
      - checkout
      - restore_cache:
          key:         ftgo-monolith-{{ checksum "gradle.properties" }}
      - run:           TERM=dumb ./gradlew testClasses
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key:         ftgo-monolith-{{ checksum "gradle.properties" }}
      - run:
          command:     |
            ./.circleci/upgrade-docker-compose.sh
            . ./setenv-circle-ci.sh
            ./build-and-test-all.sh
      - run:
          name:        Save test results
          command:     |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when:        always
      - store_test_results:
          path:        ~/junit
      - store_artifacts:
          path:        ~/junit
